¤ECHOES_FX_ID_DEFINE¤
in bool inRed=false;
¤ECHOES_FX_ID_DEFINE¤
¤ECHOES_GLOBAL_FX_VERT_DEFINE¤
out bool outRed;
¤ECHOES_GLOBAL_FX_VERT_DEFINE¤
¤ECHOES_BODY_FX_VERT_DEFINE¤
	outRed = inRed;
¤ECHOES_BODY_FX_VERT_DEFINE¤
¤ECHOES_GLOBAL_FX_FRAG_DEFINE¤
out vec4 redColor;
in bool isRed;
¤ECHOES_GLOBAL_FX_FRAG_DEFINE¤
¤ECHOES_BODY_FX_FRAG_DEFINE¤
	if(isRed)
	{
		redColor = vec4(1.0, 0.0, 0.0, 1.0);
	}
¤ECHOES_BODY_FX_FRAG_DEFINE¤