¤ECHOES_GLOBAL_FX_VERT_DEFINE¤
layout(location = 0) in vec4 position;
¤ECHOES_GLOBAL_FX_VERT_DEFINE¤
¤ECHOES_BODY_FX_VERT_DEFINE¤
	gl_Position = position;
¤ECHOES_BODY_FX_VERT_DEFINE¤
¤ECHOES_GLOBAL_FX_FRAG_DEFINE¤
out vec4 outputColor;
¤ECHOES_GLOBAL_FX_FRAG_DEFINE¤
¤ECHOES_BODY_FX_FRAG_DEFINE¤
	outputColor = vec4(1.0f, 1.0f, 0.0f, 1.0f);
¤ECHOES_BODY_FX_FRAG_DEFINE¤