¤ECHOES_FX_ID_DEFINE¤
uniform bool mvp=false;
¤ECHOES_FX_ID_DEFINE¤
¤ECHOES_FX_ACTIVATION_DEFINE¤
mvp
¤ECHOES_FX_ACTIVATION_DEFINE¤
¤ECHOES_FX_DATA_DEFINE¤
0¤
MVP¤
4¤
1¤
f¤
¤ECHOES_FX_DATA_DEFINE¤
1¤
position¤
0¤
0¤
¤ECHOES_FX_DATA_DEFINE¤
¤ECHOES_GLOBAL_FX_VERT_DEFINE¤
uniform mat4 MVP;
in vec3 position;
¤ECHOES_GLOBAL_FX_VERT_DEFINE¤
¤ECHOES_BODY_FX_VERT_DEFINE¤
	gl_Position = MVP * vec4(position, 1.0);
¤ECHOES_BODY_FX_VERT_DEFINE¤